# Uncomment and fill in any platforms you use to show a "Sponsor" button.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# github: [denfry]
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# custom: ["https://example.com/donate"]
